language: generic

services:
    - docker

before_install:
    - docker build -t echingkho/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true echingkho/docker-react npm run test

before_deploy: "echo 'ready?'"
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket: "elasticbeanstalk-us-east-1-600837116870"
    bucket_path: "docker"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    description: "Sample Application"
    edge: true
    on:
        branch: master
        
        

